name: AnthRepoSync
on: 
  push:
    # Remove the `#` below if you only want a specific branch, leave it for all pushes
    # branches:
    # - main
  workflow_dispatch:

jobs:
  RepoSync:
    runs-on: ubuntu-latest
    steps:
      - name: AnthRepoSync
        uses: Anthonykung/RepoSync@v1.4.1-Alpha
        with:
          RS_TARGET: ${{ secrets.RS_TARGET }}
          RS_PAT: ${{ secrets.RS_PAT }}
